spring.application.name=truck-booking

spring.datasource.url=jdbc:mysql://localhost:3306/truck_booking
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=7878